WorkflowManager/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WorkflowManager.Models;

namespace WorkflowManager.Controllers
{
    public class ClientsController : Controller
    {
        private readonly workflow_managerContext _context;

        public ClientsController(workflow_managerContext context)
        {
            _context = context;
        }

        public IActionResult Login()
        {
            // TempData.Keep("staffoccupationID");
            TempData["authUsername"] = "";
            TempData["authId"] = 0;
            TempData["staffoccupationID"] = 0;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(String Username, String Password)
        {
            var loginInfo = _context.Client.Where(s => s.Username == Username && s.Password == Password).FirstOrDefault();
            var staffLoginInfo = _context.Staff.Where(s => s.Username == Username && s.Password == Password).FirstOrDefault();

            if (loginInfo == null && staffLoginInfo == null)
            {
                return (RedirectToAction(nameof(Login)));
            }
            else if (loginInfo != null)
            {
                TempData["authUsername"] = loginInfo.Username;
                TempData["authId"] = loginInfo.Id;
                TempData["staffoccupationID"] = 4;
                return RedirectToAction("Details", new { id = loginInfo.Id });
            }
            else
            {
                TempData["authUsername"] = staffLoginInfo.Username;
                TempData["authId"] = staffLoginInfo.Id;
                TempData["staffoccupationID"] = staffLoginInfo.FunctiestaffId;
                return RedirectToAction("Details", "Staffs", new { id = staffLoginInfo.Id });
            }
        }

        public IActionResult Logout()
        {
            TempData["authUsername"] = "";
            TempData["authId"] = 0;
            TempData["staffoccupationID"] = 0;
            return RedirectToAction(nameof(Login));
        }

        public IActionResult Register()
        {
            return View();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register([Bind("Id,Username,Password,Nume,Prenume,Email,Telefon,Adresa,Avatar,CreateTime,UpdateTime")] Client client, String confirmPassword)
        {
            if (ModelState.IsValid && client.Password == confirmPassword)
            {
                _context.Add(client);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Login));
            }
            else if (client.Password != confirmPassword)
            {
                return RedirectToAction(nameof(Register));
            }
            return View(client);
        }

        // GET: Clients
        public async Task<IActionResult> Index()
        {
            return View(await _context.Client.ToListAsync());
        }

        // GET: Clients/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Client
                .FirstOrDefaultAsync(m => m.Id == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // GET: Clients/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Username,Password,Nume,Prenume,Email,Telefon,Adresa,Avatar,CreateTime,UpdateTime")] Client client)
        {
            if (ModelState.IsValid)
            {
                _context.Add(client);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Client.FindAsync(id);
            if (client == null)
            {
                return NotFound();
            }
            return View(client);
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Username,Password,Nume,Prenume,Email,Telefon,Adresa,Avatar,CreateTime,UpdateTime")] Client client)
        {
            if (id != client.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    client.UpdateTime = DateTime.Now;
                    _context.Update(client);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientExists(client.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Client
                .FirstOrDefaultAsync(m => m.Id == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var client = await _context.Client.FindAsync(id);
            _context.Client.Remove(client);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClientExists(int id)
        {
            return _context.Client.Any(e => e.Id == id);
        }
    }
}

WorkflowManager/Controllers/StaffsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WorkflowManager.Models;

namespace WorkflowManager.Controllers
{
    public class StaffsController : Controller
    {
        private readonly workflow_managerContext _context;

        public StaffsController(workflow_managerContext context)
        {
            _context = context;
        }

        // GET: Staffs
        public async Task<IActionResult> Index()
        {
            var workflow_managerContext = _context.Staff.Include(s => s.Echipa).Include(s => s.Functiestaff);
            return View(await workflow_managerContext.ToListAsync());
        }

        // GET: Staffs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staff = await _context.Staff
                .Include(s => s.Echipa)
                .Include(s => s.Functiestaff)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (staff == null)
            {
                return NotFound();
            }

            return View(staff);
        }

        // GET: Staffs/Create
        public IActionResult Create()
        {
            ViewData["EchipaId"] = new SelectList(_context.Echipa, "Id", "Nume");
            ViewData["FunctiestaffId"] = new SelectList(_context.Functiestaff, "Id", "Nume");
            return View();
        }

        // POST: Staffs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Username,Password,Nume,Prenume,Email,Adresa,Telefon,Avatar,CreateTime,UpdateTime,FunctiestaffId,EchipaId")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                _context.Add(staff);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EchipaId"] = new SelectList(_context.Echipa, "Id", "Nume", staff.EchipaId);
            ViewData["FunctiestaffId"] = new SelectList(_context.Functiestaff, "Id", "Nume", staff.FunctiestaffId);
            return View(staff);
        }

        // GET: Staffs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staff = await _context.Staff.FindAsync(id);
            if (staff == null)
            {
                return NotFound();
            }
            ViewData["EchipaId"] = new SelectList(_context.Echipa, "Id", "Nume", staff.EchipaId);
            ViewData["FunctiestaffId"] = new SelectList(_context.Functiestaff, "Id", "Nume", staff.FunctiestaffId);
            return View(staff);
        }

        // POST: Staffs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Username,Password,Nume,Prenume,Email,Adresa,Telefon,Avatar,CreateTime,UpdateTime,FunctiestaffId,EchipaId")] Staff staff)
        {
            if (id != staff.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    staff.UpdateTime = DateTime.Now;
                    _context.Update(staff);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StaffExists(staff.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EchipaId"] = new SelectList(_context.Echipa, "Id", "Nume", staff.EchipaId);
            ViewData["FunctiestaffId"] = new SelectList(_context.Functiestaff, "Id", "Nume", staff.FunctiestaffId);
            return View(staff);
        }

        // GET: Staffs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staff = await _context.Staff
                .Include(s => s.Echipa)
                .Include(s => s.Functiestaff)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (staff == null)
            {
                return NotFound();
            }

            return View(staff);
        }

        // POST: Staffs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var staff = await _context.Staff.FindAsync(id);
            _context.Staff.Remove(staff);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StaffExists(int id)
        {
            return _context.Staff.Any(e => e.Id == id);
        }
    }
}

WorkflowManager/Controllers/StatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WorkflowManager.Models;

namespace WorkflowManager.Controllers
{
    public class StatusController : Controller
    {
        private readonly workflow_managerContext _context;

        public StatusController(workflow_managerContext context)
        {
            _context = context;
        }

        // GET: Status
        public async Task<IActionResult> Index()
        {
            return View(await _context.Status.ToListAsync());
        }

        // GET: Status/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var status = await _context.Status
                .FirstOrDefaultAsync(m => m.Id == id);
            if (status == null)
            {
                return NotFound();
            }

            return View(status);
        }

        // GET: Status/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Status/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nume,Descriere,CreateTime,UpdateTime")] Status status)
        {
            if (ModelState.IsValid)
            {
                _context.Add(status);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(status);
        }

        // GET: Status/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var status = await _context.Status.FindAsync(id);
            if (status == null)
            {
                return NotFound();
            }
            return View(status);
        }

        // POST: Status/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nume,Descriere,CreateTime,UpdateTime")] Status status)
        {
            if (id != status.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    status.UpdateTime = DateTime.Now;
                    _context.Update(status);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StatusExists(status.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(status);
        }

        // GET: Status/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var status = await _context.Status
                .FirstOrDefaultAsync(m => m.Id == id);
            if (status == null)
            {
                return NotFound();
            }

            return View(status);
        }

        // POST: Status/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var status = await _context.Status.FindAsync(id);
            _context.Status.Remove(status);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StatusExists(int id)
        {
            return _context.Status.Any(e => e.Id == id);
        }
    }
}

WorkflowManager/Views/Shared/_ClientLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WorkflowManager - Client</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-dark bg-dark">

                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="navbar-toggler-icon"></span>
                        </button> <a class="navbar-brand" asp-area="" asp-controller="Clients" asp-action="Details" asp-route-id="@TempData["authId"]">Client</a>
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Proiectactivs" asp-action="Index">Proiecte Active</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Proiects" asp-action="Index">Proiecte</a>
                                </li>
                            </ul>
                            <ul class="navbar-nav ml-md-auto">
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Clients" asp-action="Details" asp-route-id="@TempData["authId"]">@TempData["authUsername"]</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Clients" asp-action="Logout">
                                        <i class="fas fa-sign-out-alt"></i> Logout
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ShopManagement <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/fontawesome-free-5.13.0-web/js/all.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WorkflowManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WorkflowManager - Home</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-dark bg-dark">

                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="navbar-toggler-icon"></span>
                        </button> <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Echipas" asp-action="Index">Echipe</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Proiects" asp-action="Index">Proiecte</a>
                                </li>
                            </ul>
                            <ul class="navbar-nav ml-md-auto">
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Clients" asp-action="Login"> <i class="fas fa-sign-in-alt"></i> Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Clients" asp-action="Register"><i class="fas fa-user-plus"></i> Register</a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ShopManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/fontawesome-free-5.13.0-web/js/all.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WorkflowManager/Views/Shared/_ManagerLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WorkflowManager - Manager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-dark bg-dark">

                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="navbar-toggler-icon"></span>
                        </button> <a class="navbar-brand" asp-area="" asp-controller="Staffs" asp-action="Details" asp-route-id="@TempData["authId"]">Manager</a>
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Clients" asp-action="Index">Clienti</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Comandamateriales" asp-action="Index">Comenzi</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Echipaments" asp-action="Index">Echipament</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Echipas" asp-action="Index">Echipe</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Functiestaffs" asp-action="Index">Plati</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Materiales" asp-action="Index">Materiale</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Notificaris" asp-action="Index">Notificari</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Proiectactivs" asp-action="Index">Proiecte Active</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Proiects" asp-action="Index">Proiecte</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Staffs" asp-action="Index">Staff</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Status" asp-action="Index">Status</a>
                                </li>
                            </ul>
                            <ul class="navbar-nav ml-md-auto">
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Staffs" asp-action="Details" asp-route-id="@TempData["authId"]">@TempData["authUsername"]</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Clients" asp-action="Logout">
                                        <i class="fas fa-sign-out-alt"></i> Logout
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ShopManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/fontawesome-free-5.13.0-web/js/all.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>